variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  DOCKER_AUTH_CONFIG: $DOCKER_CONFIG_JSON

stages:
  - build
  - deploy
  - test

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

deploy_int:
  variables:
    HOST: wwwint.ebi.ac.uk
  environment:
    name: primary_hl_int
    url: https://wwwint.ebi.ac.uk/biosamples/biovalidator
  when: manual
  extends: .kube_deploy_script

deploy_dev_primary:
  variables:
    HOST: wwwdev.ebi.ac.uk
  environment:
    name: primary_hl_dev
    url: https://wwwdev.ebi.ac.uk/biosamples/biovalidator
  when: manual
  extends: .kube_deploy_script

deploy_dev_fallback:
  variables:
    HOST: wwwdev.ebi.ac.uk
  environment:
    name: fallback_hx_dev
    url: https://wwwdev.ebi.ac.uk/biosamples/biovalidator
  when: manual
  extends: .kube_deploy_script

deploy_prod_primary:
  variables:
    HOST: www.ebi.ac.uk
  environment:
    name: primary_hl_prod
    url: https://www.ebi.ac.uk/biosamples/biovalidator
  when: manual
  extends: .kube_deploy_script

deploy_prod_ait_biovalidator:
  variables:
    HOST: www.ebi.ac.uk
    CONTEXT_PATH: /ait/biovalidator
    K8S_NAMESPACE: ait_biovalidator_prod
  environment:
    name: primary_hl_ait_prod
    url: https://www.ebi.ac.uk/ait/biovalidator
  when: manual
  extends: .kube_deploy_script

deploy_prod_fallback:
    variables:
      HOST: www.ebi.ac.uk
    environment:
      name: fallback_hx_prod
      url: https://www.ebi.ac.uk/biosamples/biovalidator
    when: manual
    extends: .kube_deploy_script

# todo discuss: do we need AIT biovalidator to share with others?
# todo discuss: what are the options to make biosamples internal only: remove ingress and make service=ClusterIP?
#deploy_prod_ait:
#  variables:
#    NAMESPACE: ait-prod
#    HOST: www.ebi.ac.uk
#  environment:
#    name: prod-ait
#    url: https://www.ebi.ac.uk/ait/biovalidator
#  when: manual
#  extends: .kube_deploy_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl create namespace ${K8S_NAMESPACE} || true
    - echo ${K8S_NAMESPACE}
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - envsubst < deployment.yaml > kubernetes.yaml
    - kubectl apply -f kubernetes.yaml
    - kubectl rollout restart deployments biovalidator


trigger_api_tests:
  stage: test
  when: manual
  trigger:
    project: FAIRification/biosamples-api-tests
  variables:
    BSD_ENV: "wwwint"
    FOLDER: "biovalidator"
    TRIGGER_SERVICE: "true"
